<?php

use \Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Mckenziearts\Shopper\Models\Country;

class CountriesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $countries = json_decode(file_get_contents(__DIR__. '/countries.json'), true);
        DB::table('shopper_location_countries')->delete();

        foreach ($countries as $id => $country) {
            DB::table('shopper_location_countries')->insert([
                'is_enabled' => 0,
                'code' => $country['iso_3166_2'],
                'name' => $country['name'],
                'iso_3' => $country['iso_3166_3'],
                'calling_code' => $country['calling_code'],
                'flag' => ((isset($country['flag'])) ? $country['flag'] : null),
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s')
            ]);
        }

        $cm = Country::where('code', 'CM')->first();
        $cm->update(['is_enabled' => 1]);
        $cm->states()->createMany([
            ['code' => 'CM-AD', 'name' => 'Adamaoua'],
            ['code' => 'CM-CT', 'name' => 'Centre'],
            ['code' => 'CM-ES', 'name' => 'Est'],
            ['code' => 'CM-EN', 'name' => 'Extrême-Nord'],
            ['code' => 'CM-LT', 'name' => 'Littoral'],
            ['code' => 'CM-ND', 'name' => 'Nord'],
            ['code' => 'CM-NO', 'name' => 'Nord-Ouest'],
            ['code' => 'CM-OU', 'name' => 'Ouest'],
            ['code' => 'CM-SD', 'name' => 'Sud'],
            ['code' => 'CM-SO', 'name' => 'Sud-Ouest'],
        ]);

        $us = Country::where('code', 'US')->first();
        $us->update(['is_enabled' => 1]);
        $us->states()->createMany([
            ['code' => 'AL', 'name' => 'Alabama'],
            ['code' => 'AK', 'name' => 'Alaska'],
            ['code' => 'AS', 'name' => 'American Samoa'],
            ['code' => 'AZ', 'name' => 'Arizona'],
            ['code' => 'AR', 'name' => 'Arkansas'],
            ['code' => 'CA', 'name' => 'California'],
            ['code' => 'CO', 'name' => 'Colorado'],
            ['code' => 'CT', 'name' => 'Connecticut'],
            ['code' => 'DE', 'name' => 'Delaware'],
            ['code' => 'DC', 'name' => 'Dist. of Columbia'],
            ['code' => 'FL', 'name' => 'Florida'],
            ['code' => 'GA', 'name' => 'Georgia'],
            ['code' => 'GU', 'name' => 'Guam'],
            ['code' => 'HI', 'name' => 'Hawaii'],
            ['code' => 'ID', 'name' => 'Idaho'],
            ['code' => 'IL', 'name' => 'Illinois'],
            ['code' => 'IN', 'name' => 'Indiana'],
            ['code' => 'IA', 'name' => 'Iowa'],
            ['code' => 'KS', 'name' => 'Kansas'],
            ['code' => 'KY', 'name' => 'Kentucky'],
            ['code' => 'LA', 'name' => 'Louisiana'],
            ['code' => 'ME', 'name' => 'Maine'],
            ['code' => 'MD', 'name' => 'Maryland'],
            ['code' => 'MH', 'name' => 'Marshall Islands'],
            ['code' => 'MA', 'name' => 'Massachusetts'],
            ['code' => 'MI', 'name' => 'Michigan'],
            ['code' => 'FM', 'name' => 'Micronesia'],
            ['code' => 'MN', 'name' => 'Minnesota'],
            ['code' => 'MS', 'name' => 'Mississippi'],
            ['code' => 'MO', 'name' => 'Missouri'],
            ['code' => 'MT', 'name' => 'Montana'],
            ['code' => 'NE', 'name' => 'Nebraska'],
            ['code' => 'NV', 'name' => 'Nevada'],
            ['code' => 'NH', 'name' => 'New Hampshire'],
            ['code' => 'NJ', 'name' => 'New Jersey'],
            ['code' => 'NM', 'name' => 'New Mexico'],
            ['code' => 'NY', 'name' => 'New York'],
            ['code' => 'NC', 'name' => 'North Carolina'],
            ['code' => 'ND', 'name' => 'North Dakota'],
            ['code' => 'MP', 'name' => 'Northern Marianas'],
            ['code' => 'OH', 'name' => 'Ohio'],
            ['code' => 'OK', 'name' => 'Oklahoma'],
            ['code' => 'OR', 'name' => 'Oregon'],
            ['code' => 'PW', 'name' => 'Palau'],
            ['code' => 'PA', 'name' => 'Pennsylvania'],
            ['code' => 'PR', 'name' => 'Puerto Rico'],
            ['code' => 'RI', 'name' => 'Rhode Island'],
            ['code' => 'SC', 'name' => 'South Carolina'],
            ['code' => 'SD', 'name' => 'South Dakota'],
            ['code' => 'TN', 'name' => 'Tennessee'],
            ['code' => 'TX', 'name' => 'Texas'],
            ['code' => 'UT', 'name' => 'Utah'],
            ['code' => 'VT', 'name' => 'Vermont'],
            ['code' => 'VA', 'name' => 'Virginia'],
            ['code' => 'VI', 'name' => 'Virgin Islands'],
            ['code' => 'WA', 'name' => 'Washington'],
            ['code' => 'WV', 'name' => 'West Virginia'],
            ['code' => 'WI', 'name' => 'Wisconsin'],
            ['code' => 'WY', 'name' => 'Wyoming']
        ]);

        $ca = Country::where('code', 'CA')->first();
        $ca->update(['is_enabled' => 1]);
        $ca->states()->createMany([
            ['code' => 'AB', 'name' => 'Alberta'],
            ['code' => 'BC', 'name' => 'British Columbia'],
            ['code' => 'MB', 'name' => 'Manitoba'],
            ['code' => 'NB', 'name' => 'New Brunswick'],
            ['code' => 'NL', 'name' => 'Newfoundland and Labrador'],
            ['code' => 'NT', 'name' => 'Northwest Territories'],
            ['code' => 'NS', 'name' => 'Nova Scotia'],
            ['code' => 'NU', 'name' => 'Nunavut'],
            ['code' => 'ON', 'name' => 'Ontario'],
            ['code' => 'PE', 'name' => 'Prince Edward Island'],
            ['code' => 'QC', 'name' => 'Quebec'],
            ['code' => 'SK', 'name' => 'Saskatchewan'],
            ['code' => 'YT', 'name' => 'Yukon']
        ]);

        $fr = Country::where('code', 'FR')->first();
        $fr->update(['is_enabled' => 1]);
        $fr->states()->createMany([
            ['code' => 'ARA',  'name' => 'Auvergne-Rhône-Alpes'],
            ['code' => 'BFC',  'name' => 'Bourgogne-Franche-Comté'],
            ['code' => 'BZH',  'name' => 'Bretagne'],
            ['code' => 'CVL',  'name' => 'Centre–Val-de-Loire'],
            ['code' => 'COR',  'name' => 'Corse'],
            ['code' => 'GP',   'name' => 'Guadeloupe'],
            ['code' => 'GF',   'name' => 'Guyane'],
            ['code' => 'GE',   'name' => 'Grand-Est'],
            ['code' => 'HF',   'name' => 'Hauts-de-France'],
            ['code' => 'IDF',  'name' => 'Île-de-France'],
            ['code' => 'MQ',   'name' => 'Martinique'],
            ['code' => 'YT',   'name' => 'Mayotte'],
            ['code' => 'NOR',  'name' => 'Normandie'],
            ['code' => 'PL',   'name' => 'Pays-de-la-Loire'],
            ['code' => 'NA',   'name' => 'Nouvelle-Aquitaine'],
            ['code' => 'OCC',  'name' => 'Occitanie'],
            ['code' => 'PACA', 'name' => 'Provence-Alpes-Côte-d\'Azur'],
            ['code' => 'RE',   'name' => 'Réunion'],
        ]);

        $au = Country::where('code', 'AU')->first();
        $au->update(['is_enabled' => 1]);
        $au->states()->createMany([
            ['code' => 'NSW', 'name' => 'New South Wales'],
            ['code' => 'QLD', 'name' => 'Queensland'],
            ['code' => 'SA', 'name' => 'South Australia'],
            ['code' => 'TAS', 'name' => 'Tasmania'],
            ['code' => 'VIC', 'name' => 'Victoria'],
            ['code' => 'WA', 'name' => 'Western Australia'],
            ['code' => 'NT', 'name' => 'Northern Territory'],
            ['code' => 'ACT', 'name' => 'Australian Capital Territory']
        ]);

        $gb = Country::where('code', 'GB')->first();
        $gb->update(['is_enabled' => 1]);
        $gb->states()->createMany([
            ['code' => 'ABE', 'name' => 'Aberdeenshire'],
            ['code' => 'ALY', 'name' => 'Anglesey'],
            ['code' => 'ANG', 'name' => 'Angus'],
            ['code' => 'ARG', 'name' => 'Argyll'],
            ['code' => 'AYR', 'name' => 'Ayrshire'],
            ['code' => 'BAN', 'name' => 'Banffshire'],
            ['code' => 'BED', 'name' => 'Bedfordshire'],
            ['code' => 'BER', 'name' => 'Berkshire'],
            ['code' => 'BWS', 'name' => 'Berwickshire'],
            ['code' => 'BRE', 'name' => 'Brecknockshire'],
            ['code' => 'BUC', 'name' => 'Buckinghamshire'],
            ['code' => 'BUT', 'name' => 'Bute'],
            ['code' => 'CAE', 'name' => 'Caernarfonshire'],
            ['code' => 'CAI', 'name' => 'Caithness'],
            ['code' => 'CAM', 'name' => 'Cambridgeshire'],
            ['code' => 'CAR', 'name' => 'Cardiganshire'],
            ['code' => 'CMS', 'name' => 'Carmarthenshire'],
            ['code' => 'CHE', 'name' => 'Cheshire'],
            ['code' => 'CLA', 'name' => 'Clackmannanshire'],
            ['code' => 'CLE', 'name' => 'Cleveland'],
            ['code' => 'COR', 'name' => 'Cornwall'],
            ['code' => 'CRO', 'name' => 'Cromartyshire'],
            ['code' => 'CBR', 'name' => 'Cumberland'],
            ['code' => 'CUM', 'name' => 'Cumbria'],
            ['code' => 'DEN', 'name' => 'Denbighshire'],
            ['code' => 'DER', 'name' => 'Derbyshire'],
            ['code' => 'DEV', 'name' => 'Devon'],
            ['code' => 'DOR', 'name' => 'Dorset'],
            ['code' => 'DBS', 'name' => 'Dumbartonshire'],
            ['code' => 'DUM', 'name' => 'Dumfriesshire'],
            ['code' => 'DUR', 'name' => 'Durham'],
            ['code' => 'ELO', 'name' => 'East Lothian'],
            ['code' => 'ESS', 'name' => 'Essex'],
            ['code' => 'FLI', 'name' => 'Flintshire'],
            ['code' => 'FIF', 'name' => 'Fife'],
            ['code' => 'GLA', 'name' => 'Glamorgan'],
            ['code' => 'GLO', 'name' => 'Gloucestershire'],
            ['code' => 'HAM', 'name' => 'Hampshire'],
            ['code' => 'HER', 'name' => 'Herefordshire'],
            ['code' => 'HTF', 'name' => 'Hertfordshire'],
            ['code' => 'HUN', 'name' => 'Huntingdonshire'],
            ['code' => 'INV', 'name' => 'Inverness'],
            ['code' => 'KEN', 'name' => 'Kent'],
            ['code' => 'KCD', 'name' => 'Kincardineshire'],
            ['code' => 'KIN', 'name' => 'Kinross-shire'],
            ['code' => 'KIR', 'name' => 'Kirkcudbrightshire'],
            ['code' => 'LKS', 'name' => 'Lanarkshire'],
            ['code' => 'LAN', 'name' => 'Lancashire'],
            ['code' => 'LEI', 'name' => 'Leicestershire'],
            ['code' => 'LIN', 'name' => 'Lincolnshire'],
            ['code' => 'LON', 'name' => 'London'],
            ['code' => 'MAN', 'name' => 'Manchester'],
            ['code' => 'MER', 'name' => 'Merionethshire'],
            ['code' => 'MSY', 'name' => 'Merseyside'],
            ['code' => 'MDX', 'name' => 'Middlesex'],
            ['code' => 'MID', 'name' => 'Midlands'],
            ['code' => 'MLT', 'name' => 'Midlothian'],
            ['code' => 'MON', 'name' => 'Monmouthshire'],
            ['code' => 'MGY', 'name' => 'Montgomeryshire'],
            ['code' => 'MOR', 'name' => 'Moray'],
            ['code' => 'NAI', 'name' => 'Nairnshire'],
            ['code' => 'NOR', 'name' => 'Norfolk'],
            ['code' => 'NMP', 'name' => 'Northamptonshire'],
            ['code' => 'NUM', 'name' => 'Northumberland'],
            ['code' => 'NOT', 'name' => 'Nottinghamshire'],
            ['code' => 'ORK', 'name' => 'Orkney'],
            ['code' => 'OXF', 'name' => 'Oxfordshire'],
            ['code' => 'PEE', 'name' => 'Peebleshire'],
            ['code' => 'PEM', 'name' => 'Pembrokeshire'],
            ['code' => 'PER', 'name' => 'Perthshire'],
            ['code' => 'RAD', 'name' => 'Radnorshire'],
            ['code' => 'REN', 'name' => 'Renfrewshire'],
            ['code' => 'ROS', 'name' => 'Ross & Cromarty'],
            ['code' => 'ROX', 'name' => 'Roxburghshire'],
            ['code' => 'RUT', 'name' => 'Rutland'],
            ['code' => 'SEL', 'name' => 'Selkirkshire'],
            ['code' => 'SHE', 'name' => 'Shetland'],
            ['code' => 'SHR', 'name' => 'Shropshire'],
            ['code' => 'SOM', 'name' => 'Somerset'],
            ['code' => 'STA', 'name' => 'Staffordshire'],
            ['code' => 'STI', 'name' => 'Stirlingshire'],
            ['code' => 'SUF', 'name' => 'Suffolk'],
            ['code' => 'SUR', 'name' => 'Surrey'],
            ['code' => 'SUS', 'name' => 'Sussex'],
            ['code' => 'SUT', 'name' => 'Sutherland'],
            ['code' => 'TYN', 'name' => 'Tyne & Wear'],
            ['code' => 'WAR', 'name' => 'Warwickshire'],
            ['code' => 'WLO', 'name' => 'West Lothian'],
            ['code' => 'WES', 'name' => 'Westmorland'],
            ['code' => 'WIG', 'name' => 'Wigtownshire'],
            ['code' => 'WIL', 'name' => 'Wiltshire'],
            ['code' => 'WOR', 'name' => 'Worcestershire'],
            ['code' => 'YOR', 'name' => 'Yorkshire']
        ]);

        $br = Country::where('code', 'BR')->first();
        $br->states()->createMany([
            ['code' => 'AC', 'name' => 'Acre'],
            ['code' => 'AL', 'name' => 'Alagoas'],
            ['code' => 'AP', 'name' => 'Amapá'],
            ['code' => 'AM', 'name' => 'Amazonas'],
            ['code' => 'BA', 'name' => 'Bahia'],
            ['code' => 'CE', 'name' => 'Ceará'],
            ['code' => 'DF', 'name' => 'Distrito Federal'],
            ['code' => 'ES', 'name' => 'Espírito Santo'],
            ['code' => 'GO', 'name' => 'Goiás'],
            ['code' => 'MA', 'name' => 'Maranhão'],
            ['code' => 'MT', 'name' => 'Mato Grosso'],
            ['code' => 'MS', 'name' => 'Mato Grosso do Sul'],
            ['code' => 'MG', 'name' => 'Minas Gerais'],
            ['code' => 'PA', 'name' => 'Pará'],
            ['code' => 'PB', 'name' => 'Paraíba'],
            ['code' => 'PR', 'name' => 'Paraná'],
            ['code' => 'PE', 'name' => 'Pernambuco'],
            ['code' => 'PI', 'name' => 'Piauí'],
            ['code' => 'RJ', 'name' => 'Rio de Janeiro'],
            ['code' => 'RN', 'name' => 'Rio Grande do Norte'],
            ['code' => 'RS', 'name' => 'Rio Grande do Sul'],
            ['code' => 'RO', 'name' => 'Rondônia'],
            ['code' => 'RR', 'name' => 'Roraima'],
            ['code' => 'SC', 'name' => 'Santa Catarina'],
            ['code' => 'SP', 'name' => 'São Paulo'],
            ['code' => 'SE', 'name' => 'Sergipe'],
            ['code' => 'TO', 'name' => 'Tocantins']
        ]);

        $ca = Country::where('code', 'CH')->first();
        $ca->states()->createMany([
            ['code' => 'AG', 'name' => 'Aargau'],
            ['code' => 'AI', 'name' => 'Appenzell Innerrhoden'],
            ['code' => 'AR', 'name' => 'Appenzell Ausserrhoden'],
            ['code' => 'BE', 'name' => 'Bern'],
            ['code' => 'BL', 'name' => 'Basel-Landschaft'],
            ['code' => 'BS', 'name' => 'Basel-Stadt'],
            ['code' => 'FR', 'name' => 'Fribourg'],
            ['code' => 'GE', 'name' => 'Genève'],
            ['code' => 'GL', 'name' => 'Glarus'],
            ['code' => 'GR', 'name' => 'Graubünden'],
            ['code' => 'JU', 'name' => 'Jura'],
            ['code' => 'LU', 'name' => 'Luzern'],
            ['code' => 'NE', 'name' => 'Neuchâtel'],
            ['code' => 'NW', 'name' => 'Nidwalden'],
            ['code' => 'OW', 'name' => 'Obwalden'],
            ['code' => 'SG', 'name' => 'St. Gallen'],
            ['code' => 'SO', 'name' => 'Solothurn'],
            ['code' => 'SZ', 'name' => 'Schwyz'],
            ['code' => 'TG', 'name' => 'Thurgau'],
            ['code' => 'TI', 'name' => 'Ticino'],
            ['code' => 'UR', 'name' => 'Uri'],
            ['code' => 'VD', 'name' => 'Vaud'],
            ['code' => 'VS', 'name' => 'Valais'],
            ['code' => 'ZG', 'name' => 'Zug'],
            ['code' => 'ZH', 'name' => 'Zürich']
        ]);

        $de = Country::where('code', 'DE')->first();
        $de->states()->createMany([
            ['code' => 'BW', 'name' => 'Baden-Württemberg'],
            ['code' => 'BY', 'name' => 'Bavaria'],
            ['code' => 'BE', 'name' => 'Berlin'],
            ['code' => 'BB', 'name' => 'Brandenburg'],
            ['code' => 'HB', 'name' => 'Bremen'],
            ['code' => 'HH', 'name' => 'Hamburg'],
            ['code' => 'HE', 'name' => 'Hesse'],
            ['code' => 'MV', 'name' => 'Mecklenburg-Vorpommern'],
            ['code' => 'NI', 'name' => 'Lower Saxony'],
            ['code' => 'NW', 'name' => 'North Rhine-Westphalia'],
            ['code' => 'RP', 'name' => 'Rhineland-Palatinate'],
            ['code' => 'SL', 'name' => 'Saarland'],
            ['code' => 'SN', 'name' => 'Saxony'],
            ['code' => 'ST', 'name' => 'Saxony-Anhalt'],
            ['code' => 'SH', 'name' => 'Schleswig-Holstein'],
            ['code' => 'TH', 'name' => 'Thuringia']
        ]);

        $ee = Country::where('code', 'EE')->first();
        $ee->states()->createMany([
            ['code' => 'HA', 'name' => 'Harju'],
            ['code' => 'HI', 'name' => 'Hiiu'],
            ['code' => 'IV', 'name' => 'Ida-Viru'],
            ['code' => 'JR', 'name' => 'Jõgeva'],
            ['code' => 'JN', 'name' => 'Järva'],
            ['code' => 'LN', 'name' => 'Lääne'],
            ['code' => 'LV', 'name' => 'Lääne-Viru'],
            ['code' => 'PL', 'name' => 'Põlva'],
            ['code' => 'PR', 'name' => 'Pärnu'],
            ['code' => 'RA', 'name' => 'Rapla'],
            ['code' => 'SA', 'name' => 'Saare'],
            ['code' => 'TA', 'name' => 'Tartu'],
            ['code' => 'VG', 'name' => 'Valga'],
            ['code' => 'VD', 'name' => 'Viljandi'],
            ['code' => 'VR', 'name' => 'Võru']
        ]);

        $ie = Country::where('code', 'IE')->first();
        $ie->states()->createMany([
            ['code' => 'D', 'name' => 'Dublin'],
            ['code' => 'WW', 'name' => 'Wicklow'],
            ['code' => 'WX', 'name' => 'Wexford'],
            ['code' => 'CW', 'name' => 'Carlow'],
            ['code' => 'KE', 'name' => 'Kildare'],
            ['code' => 'MH', 'name' => 'Meath'],
            ['code' => 'LH', 'name' => 'Louth'],
            ['code' => 'MN', 'name' => 'Monaghan'],
            ['code' => 'CN', 'name' => 'Cavan'],
            ['code' => 'LD', 'name' => 'Longford'],
            ['code' => 'WH', 'name' => 'Westmeath'],
            ['code' => 'OY', 'name' => 'Offaly'],
            ['code' => 'LS', 'name' => 'Laois'],
            ['code' => 'KK', 'name' => 'Kilkenny'],
            ['code' => 'WD', 'name' => 'Waterford'],
            ['code' => 'C', 'name' => 'Cork'],
            ['code' => 'KY', 'name' => 'Kerry'],
            ['code' => 'LK', 'name' => 'Limerick'],
            ['code' => 'TN', 'name' => 'North Tipperary'],
            ['code' => 'TS', 'name' => 'South Tipperary'],
            ['code' => 'CE', 'name' => 'Clare'],
            ['code' => 'G', 'name' => 'Galway'],
            ['code' => 'MO', 'name' => 'Mayo'],
            ['code' => 'RN', 'name' => 'Roscommon'],
            ['code' => 'SO', 'name' => 'Sligo'],
            ['code' => 'LM', 'name' => 'Leitrim'],
            ['code' => 'DL', 'name' => 'Donegal']
        ]);

        $nl = Country::where('code', 'NL')->first();
        $nl->states()->createMany([
            ['code' => 'DR', 'name' => 'Drenthe'],
            ['code' => 'FL', 'name' => 'Flevoland'],
            ['code' => 'FR', 'name' => 'Friesland'],
            ['code' => 'GE', 'name' => 'Gelderland'],
            ['code' => 'GR', 'name' => 'Groningen'],
            ['code' => 'LI', 'name' => 'Limburg'],
            ['code' => 'NB', 'name' => 'Noord-Brabant'],
            ['code' => 'NH', 'name' => 'Noord-Holland'],
            ['code' => 'OV', 'name' => 'Overijssel'],
            ['code' => 'UT', 'name' => 'Utrecht'],
            ['code' => 'ZE', 'name' => 'Zeeland'],
            ['code' => 'ZH', 'name' => 'Zuid-Holland']
        ]);

        $ro = Country::where('code', 'RO')->first();
        $ro->states()->createMany([
            ['code' => 'AB', 'name' => 'Alba'],
            ['code' => 'AR', 'name' => 'Arad'],
            ['code' => 'AG', 'name' => 'Arges'],
            ['code' => 'BC', 'name' => 'Bacău'],
            ['code' => 'BH', 'name' => 'Bihor'],
            ['code' => 'BN', 'name' => 'Bistrita - Nasaud Bistrita'],
            ['code' => 'BT', 'name' => 'Botosani'],
            ['code' => 'BV', 'name' => 'Brasov'],
            ['code' => 'BR', 'name' => 'Braila'],
            ['code' => 'B', 'name' => 'Bucuresti'],
            ['code' => 'BZ', 'name' => 'Buzau'],
            ['code' => 'CS', 'name' => 'Caras - Severin'],
            ['code' => 'CL', 'name' => 'Calarasi'],
            ['code' => 'CJ', 'name' => 'Cluj'],
            ['code' => 'CT', 'name' => 'Constanta'],
            ['code' => 'CV', 'name' => 'Covasna Sfantu Gheorghe'],
            ['code' => 'DB', 'name' => 'Dambovita'],
            ['code' => 'DJ', 'name' => 'Dolj'],
            ['code' => 'GL', 'name' => 'Galati'],
            ['code' => 'GR', 'name' => 'Giurgiu'],
            ['code' => 'GJ', 'name' => 'Gorj'],
            ['code' => 'HR', 'name' => 'Harghita'],
            ['code' => 'HD', 'name' => 'Hunedoara'],
            ['code' => 'IL', 'name' => 'Ialomita'],
            ['code' => 'IS', 'name' => 'Iasi'],
            ['code' => 'IF', 'name' => 'Ilfov'],
            ['code' => 'MM', 'name' => 'Maramures'],
            ['code' => 'MH', 'name' => 'Mehedinti'],
            ['code' => 'MS', 'name' => 'Mures'],
            ['code' => 'NT', 'name' => 'Neamt'],
            ['code' => 'OT', 'name' => 'Olt'],
            ['code' => 'PH', 'name' => 'Prahova Ploiesti'],
            ['code' => 'SM', 'name' => 'Satu Mare'],
            ['code' => 'SJ', 'name' => 'Salaj'],
            ['code' => 'SB', 'name' => 'Sibiu'],
            ['code' => 'SV', 'name' => 'Suceava'],
            ['code' => 'TR', 'name' => 'Teleorman'],
            ['code' => 'TM', 'name' => 'Timis'],
            ['code' => 'TL', 'name' => 'Tulcea'],
            ['code' => 'VS', 'name' => 'Vaslui'],
            ['code' => 'VL', 'name' => 'Valcea'],
            ['code' => 'VN', 'name' => 'Vrancea']
        ]);

        $hu = Country::where('code', 'HU')->first();
        $hu->states()->createMany([
            ['code' => 'BUD', 'name' => 'Budapest'],
            ['code' => 'BAR', 'name' => 'Baranya'],
            ['code' => 'BKM', 'name' => 'Bács-Kiskun'],
            ['code' => 'BEK', 'name' => 'Békés'],
            ['code' => 'BAZ', 'name' => 'Borsod-Abaúj-Zemplén'],
            ['code' => 'CSO', 'name' => 'Csongrád'],
            ['code' => 'FEJ', 'name' => 'Fejér'],
            ['code' => 'GMS', 'name' => 'Győr-Moson-Sopron'],
            ['code' => 'HBM', 'name' => 'Hajdú-Bihar'],
            ['code' => 'HEV', 'name' => 'Heves'],
            ['code' => 'JNS', 'name' => 'Jász-Nagykun-Szolnok'],
            ['code' => 'KEM', 'name' => 'Komárom-Esztergom'],
            ['code' => 'NOG', 'name' => 'Nógrád'],
            ['code' => 'PES', 'name' => 'Pest'],
            ['code' => 'SOM', 'name' => 'Somogy'],
            ['code' => 'SSB', 'name' => 'Szabolcs-Szatmár-Bereg'],
            ['code' => 'TOL', 'name' => 'Tolna'],
            ['code' => 'VAS', 'name' => 'Vas'],
            ['code' => 'VES', 'name' => 'Veszprém'],
            ['code' => 'ZAL', 'name' => 'Zala']
        ]);

        $in = Country::where('code', 'IN')->first();
        $in->states()->createMany([
            ['code' => 'AP', 'name' => 'Andhra Pradesh'],
            ['code' => 'AR', 'name' => 'Arunachal Pradesh'],
            ['code' => 'AS', 'name' => 'Assam'],
            ['code' => 'BR', 'name' => 'Bihar'],
            ['code' => 'CT', 'name' => 'Chhattisgarh'],
            ['code' => 'GA', 'name' => 'Goa'],
            ['code' => 'GJ', 'name' => 'Gujarat'],
            ['code' => 'HR', 'name' => 'Haryana'],
            ['code' => 'HP', 'name' => 'Himachal Pradesh'],
            ['code' => 'JK', 'name' => 'Jammu and Kashmir'],
            ['code' => 'JH', 'name' => 'Jharkhand'],
            ['code' => 'KA', 'name' => 'Karnataka'],
            ['code' => 'KL', 'name' => 'Kerala'],
            ['code' => 'MP', 'name' => 'Madhya Pradesh'],
            ['code' => 'MH', 'name' => 'Maharashtra'],
            ['code' => 'MN', 'name' => 'Manipur'],
            ['code' => 'ML', 'name' => 'Meghalaya'],
            ['code' => 'MZ', 'name' => 'Mizoram'],
            ['code' => 'NL', 'name' => 'Nagaland'],
            ['code' => 'OR', 'name' => 'Odisha'],
            ['code' => 'PB', 'name' => 'Punjab'],
            ['code' => 'RJ', 'name' => 'Rajasthan'],
            ['code' => 'SK', 'name' => 'Sikkim'],
            ['code' => 'TN', 'name' => 'Tamil Nadu'],
            ['code' => 'TG', 'name' => 'Telangana'],
            ['code' => 'TR', 'name' => 'Tripura'],
            ['code' => 'UT', 'name' => 'Uttarakhand'],
            ['code' => 'UP', 'name' => 'Uttar Pradesh'],
            ['code' => 'WB', 'name' => 'West Bengal'],
            ['code' => 'AN', 'name' => 'Andaman and Nicobar Islands'],
            ['code' => 'CH', 'name' => 'Chandigarh'],
            ['code' => 'DN', 'name' => 'Dadra and Nagar Haveli'],
            ['code' => 'DD', 'name' => 'Daman and Diu'],
            ['code' => 'DL', 'name' => 'Delhi'],
            ['code' => 'LD', 'name' => 'Lakshadweep'],
            ['code' => 'PY', 'name' => 'Puducherry']
        ]);

        $nz = Country::where('code', 'NZ')->first();
        $nz->states()->createMany([
            ['code' => 'NTL', 'name' => "Northland"],
            ['code' => 'AUK', 'name' => "Auckland"],
            ['code' => 'WKO', 'name' => "Waikato"],
            ['code' => 'BOP', 'name' => "Bay of Plenty"],
            ['code' => 'GIS', 'name' => "Gisborne"],
            ['code' => 'HKB', 'name' => "Hawke's Bay"],
            ['code' => 'TKI', 'name' => "Taranaki"],
            ['code' => 'MWT', 'name' => "Manawatu-Wanganui"],
            ['code' => 'WGN', 'name' => "Wellington"],
            ['code' => 'TAS', 'name' => "Tasman"],
            ['code' => 'NSN', 'name' => "Nelson"],
            ['code' => 'MBH', 'name' => "Marlborough"],
            ['code' => 'WTC', 'name' => "West Coast"],
            ['code' => 'CAN', 'name' => "Canterbury"],
            ['code' => 'OTA', 'name' => "Otago Otago"],
            ['code' => 'STL', 'name' => "Southland"],
        ]);

        $es = Country::where('code', 'ES')->first();
        $es->states()->createMany([
            ['code' => 'ES-C'	, 'name' => "A Coruña (gl) [La Coruña]"],
            ['code' => 'ES-VI'	, 'name' => "Araba (eu)"],
            ['code' => 'ES-AB'	, 'name' => "Albacete"],
            ['code' => 'ES-A'	, 'name' => "Alacant (ca)"],
            ['code' => 'ES-AL'	, 'name' => "Almería"],
            ['code' => 'ES-O'	, 'name' => "Asturias"],
            ['code' => 'ES-AV'	, 'name' => "Ávila"],
            ['code' => 'ES-BA'	, 'name' => "Badajoz"],
            ['code' => 'ES-PM'	, 'name' => "Balears (ca) [Baleares]"],
            ['code' => 'ES-B'	, 'name' => "Barcelona [Barcelona]"],
            ['code' => 'ES-BU'	, 'name' => "Burgos"],
            ['code' => 'ES-CC'	, 'name' => "Cáceres"],
            ['code' => 'ES-CA'	, 'name' => "Cádiz"],
            ['code' => 'ES-S'	, 'name' => "Cantabria"],
            ['code' => 'ES-CS'	, 'name' => "Castelló (ca)"],
            ['code' => 'ES-CR'	, 'name' => "Ciudad Real"],
            ['code' => 'ES-CO'	, 'name' => "Córdoba"],
            ['code' => 'ES-CU'	, 'name' => "Cuenca"],
            ['code' => 'ES-GI'	, 'name' => "Girona (ca) [Gerona]"],
            ['code' => 'ES-GR'	, 'name' => "Granada"],
            ['code' => 'ES-GU'	, 'name' => "Guadalajara"],
            ['code' => 'ES-SS'	, 'name' => "Gipuzkoa (eu)"],
            ['code' => 'ES-H'	, 'name' => "Huelva"],
            ['code' => 'ES-HU'	, 'name' => "Huesca"],
            ['code' => 'ES-J'	, 'name' => "Jaén"],
            ['code' => 'ES-LO'	, 'name' => "La Rioja"],
            ['code' => 'ES-GC'	, 'name' => "Las Palmas"],
            ['code' => 'ES-LE'	, 'name' => "León"],
            ['code' => 'ES-L'	, 'name' => "Lleida (ca) [Lérida]"],
            ['code' => 'ES-LU'	, 'name' => "Lugo (gl) [Lugo]"],
            ['code' => 'ES-M'	, 'name' => "Madrid"],
            ['code' => 'ES-MA'	, 'name' => "Málaga"],
            ['code' => 'ES-MU'	, 'name' => "Murcia"],
            ['code' => 'ES-NA'	, 'name' => "Nafarroa (eu)"],
            ['code' => 'ES-OR'	, 'name' => "Ourense (gl) [Orense]"],
            ['code' => 'ES-P'	, 'name' => "Palencia"],
            ['code' => 'ES-PO'	, 'name' => "Pontevedra (gl) [Pontevedra]"],
            ['code' => 'ES-SA'	, 'name' => "Salamanca"],
            ['code' => 'ES-TF'	, 'name' => "Santa Cruz de Tenerife"],
            ['code' => 'ES-SG'	, 'name' => "Segovia"],
            ['code' => 'ES-SE'	, 'name' => "Sevilla"],
            ['code' => 'ES-SO'	, 'name' => "Soria"],
            ['code' => 'ES-T'	, 'name' => "Tarragona (ca) [Tarragona]"],
            ['code' => 'ES-TE'	, 'name' => "Teruel"],
            ['code' => 'ES-TO'	, 'name' => "Toledo"],
            ['code' => 'ES-V'	, 'name' => "València (ca)"],
            ['code' => 'ES-VA'	, 'name' => "Valladolid"],
            ['code' => 'ES-BI'	, 'name' => "Bizkaia (eu)"],
            ['code' => 'ES-ZA'	, 'name' => "Zamora"],
            ['code' => 'ES-Z'	, 'name' => "Zaragoza"],
        ]);

        $mx = Country::where('code', 'MX')->first();
        $mx->states()->createMany([
            ["code" => "MX-AGU", "name" => "Aguascalientes"],
            ["code" => "MX-BCN", "name" => "Baja California"],
            ["code" => "MX-BCS", "name" => "Baja California Sur"],
            ["code" => "MX-CAM", "name" => "Campeche"],
            ["code" => "MX-CHP", "name" => "Chiapas"],
            ["code" => "MX-CHH", "name" => "Chihuahua"],
            ["code" => "MX-COA", "name" => "Coahuila"],
            ["code" => "MX-COL", "name" => "Colima"],
            ["code" => "MX-CMX​", "name" => "Ciudad de México"],
            ["code" => "MX-DUR", "name" => "Durango"],
            ["code" => "MX-GUA", "name" => "Guanajuato"],
            ["code" => "MX-GRO", "name" => "Guerrero"],
            ["code" => "MX-HID", "name" => "Hidalgo"],
            ["code" => "MX-JAL", "name" => "Jalisco"],
            ["code" => "MX-MEX", "name" => "Estado de México"],
            ["code" => "MX-MIC", "name" => "Michoacán"],
            ["code" => "MX-MOR", "name" => "Morelos"],
            ["code" => "MX-NAY", "name" => "Nayarit"],
            ["code" => "MX-NLE", "name" => "Nuevo León"],
            ["code" => "MX-OAX", "name" => "Oaxaca"],
            ["code" => "MX-PUE", "name" => "Puebla"],
            ["code" => "MX-QUE", "name" => "Querétaro"],
            ["code" => "MX-ROO", "name" => "Quintana Roo"],
            ["code" => "MX-SLP", "name" => "San Luis Potosí"],
            ["code" => "MX-SIN", "name" => "Sinaloa"],
            ["code" => "MX-SON", "name" => "Sonora"],
            ["code" => "MX-TAB", "name" => "Tabasco"],
            ["code" => "MX-TAM", "name" => "Tamaulipas"],
            ["code" => "MX-TLA", "name" => "Tlaxcala"],
            ["code" => "MX-VER", "name" => "Veracruz"],
            ["code" => "MX-YUC", "name" => "Yucatán"],
            ["code" => "MX-ZAC", "name" => "Zacatecas"]
        ]);
    }
}
